name: build
on: [push]
jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-java
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action
      - name: Build with Gradle
        uses: gradle/gradle-build-action
        with:
          arguments: build